### ISSUE TITLE
adding createChat

### ISSUE THREAD

**Issue by diego77777** [goodmind/telegram.link#15]
I'm trying to add a createChat method. I installed termgram in `termgram` folder;
I added in `termgram/lib/use-case/chat.js`
```
var api = require('telegram.link')();
                    var user1 = new api.type.InputPeerContact({
                            props: {
                                user_id: 1234567
                            }
                        }),
                        user2 = new api.type.InputPeerContact({
                            props: {
                                user_id: 7654321
                            }
                        });

var cb = function() {
                        console.log("doing the callback");
                    };

 var vector = [user1, user2];
```

`clientProxy.getClient().messages.createChat(vector, 'test', null, cb);`

------------------------------------------------------------------------------------------

then i put in `termgram/node_modules/telegram.link/lib/abi/messages.js`

```
Messages.prototype.createChat = function(users, title, callback) {
    console.log("create the cat in the hat");
    return utility.callService(api.service.messages.createChat, this.client, this.client._channel, callback, arguments);
};

```

what happens is that it prints 'create the cat in the hat' then it gives the error

```
client error TypeError: this.users.serialize is not a function
    at serialize (eval at createConstructor (/home/diego/Workshop/Essay/termgram/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:115:27), <anonymous>:12:31)
    at EncryptedRpcChannel.callMethod (/home/diego/Workshop/Essay/termgram/node_modules/telegram-mt-node/lib/net/encrypted-rpc-channel.js:165:31)
    at eval (eval at buildTypeFunction (/home/diego/Workshop/Essay/termgram/node_modules/telegram-tl-node/lib/builder/type-builder.js:104:24), <anonymous>:15:10)
    at Object.callService (/home/diego/Workshop/Essay/termgram/node_modules/telegram.link/lib/utility.js:24:13)
    at Messages.createChat (/home/diego/Workshop/Essay/termgram/node_modules/telegram.link/lib/api/messages.js:126:20)
    at /home/diego/Workshop/Essay/termgram/lib/use-case/chat.js:82:54
```

what do I need to do?

**Comment by goodmind** [comment]
I'm not maintaining termgram, only `@goodmind/telegram.link` and you seems to use original `telegram.link`

**Comment by goodmind** [comment]
@diego77777
